london:
  hosts:
    london-a:
      ansible_host: 100.104.71.17
      ansible_user: root
    london-b:
      ansible_host: 100.84.65.101
      ansible_user: root
    # london-c:    Offline for maintenance
    #   ansible_host: 100.78.115.89
    #   ansible_user: root
copenhagen:
  hosts:
    copenhagen-a:
      ansible_host: 100.119.204.12
      ansible_user: root
    copenhagen-b:
      ansible_host: 100.97.221.65
      ansible_user: root
    copenhagen-c:
      ansible_host: 100.115.45.53
      ansible_user: root
