london:
  hosts:
    london-a:
      ansible_host: 100.104.71.17
      ansible_user: root
    london-b:
      ansible_host: 100.84.65.101
      ansible_user: root
    london-c:
      ansible_host: 100.104.179.46
      ansible_user: root
copenhagen:
  hosts:
    copenhagen-a:
      ansible_host: 100.89.206.60
      ansible_user: root
    copenhagen-b:
      ansible_host: 100.107.146.142
      ansible_user: root
    copenhagen-c:
      ansible_host: 100.115.45.53
      ansible_user: root
