- hosts: all
  roles:
    - role: docker-host
    - role: shell-environment
    - role: tailscale-exit-node

- hosts: "!london-a"
  roles:
    - role: portainer-slave

- hosts:
    - london-a
    - london-b
    - copenhagen-c
  roles:
    - role: prometheus.prometheus.node_exporter

# Alpine is not supported by official node-exporter role
- hosts:
    - copenhagen-a
    - copenhagen-b
  roles:
    - role: node-exporter-docker
      vars:
        node_exporter_version: latest

- hosts: london-a
  roles:
    - role: prometheus.prometheus.alertmanager
      vars:
        alertmanager_version: latest
        alertmanager_receivers:
          - name: pagerduty
            pagerduty_configs:
              - service_key: "{{ pagerduty_service_key }}"
        alertmanager_route:
          group_by: ['alertname']
          group_wait: 10s
          group_interval: 5m
          repeat_interval: 3h
          receiver: pagerduty
          routes:
            - receiver: pagerduty
    - role: grafana.grafana.grafana
      vars:
        grafana_security:
          admin_user: "{{ grafana_admin_username }}"
          admin_password: "{{ grafana_admin_password }}"
        grafana_auth:
          anonymous:
            enabled: true
        grafana_datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://localhost:9090
            isDefault: true
            basicAuth: false
          - name: Prometheus (Copenhagen)
            type: prometheus
            access: proxy
            url: http://100.119.204.12:9090
            basicAuth: false
        grafana_provisioning_synced: true
    - role: prometheus.prometheus.prometheus
      vars:
        prometheus_alertmanager_config:
          - static_configs:
              - targets: ["localhost:9093"]
        prometheus_scrape_configs:
          - job_name: prometheus
            scrape_interval: 5s
            scrape_timeout: 5s
            static_configs:
              - targets: ["localhost:9090"]

          - job_name: unpoller
            static_configs:
              - targets: ["localhost:9130"]

          - job_name: transmission-exporter
            static_configs:
              - targets: ["localhost:19091"]

          - job_name: london-a
            static_configs:
              - targets: ['192.168.1.254:9100']

          - job_name: london-b
            static_configs:
              - targets: ['192.168.1.253:9100']

          - job_name: copenhagen-a
            static_configs:
              - targets: ['100.119.204.12:9100']

          - job_name: copenhagen-b
            static_configs:
              - targets: ['100.97.221.65:9100']

          - job_name: copenhagen-c
            static_configs:
              - targets: ['100.115.45.53:9100']
    - role: portainer-master
      vars:
        portainer_admin_password: "{{ portainer_admin_password }}"

- hosts: copenhagen-b
  roles:
    - role: gopher-site
  vars:
    gopher_repo_url: https://github.com/rwejlgaard/pez-gopher
