- name: "Common roles for all hosts"
  hosts: all
  roles:
    - role: docker-host
    - role: shell-environment
    - role: tailscale-exit-node

- name: "Install portainer slave on all except master"
  hosts: "!london-a"
  roles:
    - role: portainer-slave

- name: "Node-exporter on all hosts"
  hosts: all
  roles:
    - role: prometheus.prometheus.node_exporter
      vars:
        node_exporter_enabled_collectors:
          - systemd
          - processes
          - sysctl
          - ethtool
    - role: prometheus.prometheus.systemd_exporter

- name: "Monitoring stack"
  hosts: london-a
  roles:
    - role: prometheus.prometheus.alertmanager
      vars:
        alertmanager_version: latest
        alertmanager_receivers:
          - name: pagerduty
            pagerduty_configs:
              - service_key: "{{ pagerduty_service_key }}"
        alertmanager_route:
          group_by: ['alertname']
          group_wait: 10s
          group_interval: 5m
          repeat_interval: 3h
          receiver: pagerduty
          routes:
            - receiver: pagerduty
    - role: grafana.grafana.grafana
      vars:
        grafana_security:
          admin_user: "{{ grafana_admin_username }}"
          admin_password: "{{ grafana_admin_password }}"
        grafana_auth:
          anonymous:
            enabled: true
        grafana_datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://localhost:9090
            isDefault: true
            basicAuth: false
        grafana_provisioning_synced: true
    - role: prometheus.prometheus.prometheus
      vars:
        prometheus_storage_retention: "365d"
        prometheus_alertmanager_config:
          - static_configs:
              - targets: ["localhost:9093"]
        prometheus_scrape_configs:
          - job_name: prometheus
            scrape_interval: 5s
            scrape_timeout: 5s
            static_configs:
              - targets: ["localhost:9090"]

          - job_name: unpoller
            static_configs:
              - targets: ["localhost:9130"]

          - job_name: transmission-exporter
            static_configs:
              - targets: ["localhost:19091"]

          - job_name: london-a
            static_configs:
              - targets:
                  - '192.168.1.254:9100'
                  - '192.168.1.254:9558'

          - job_name: london-b
            static_configs:
              - targets:
                  - '192.168.1.253:9100'
                  - '192.168.1.253:9558'

          - job_name: london-c
            static_configs:
              - targets:
                  - '192.168.1.252:9100'
                  - '192.168.1.252:9558'

          - job_name: copenhagen-a
            static_configs:
              - targets:
                  - '100.89.206.60:9100'
                  - '100.89.206.60:9558'

          - job_name: copenhagen-b
            static_configs:
              - targets:
                  - '100.107.146.142:9100'
                  - '100.107.146.142:9558'

          - job_name: copenhagen-c
            static_configs:
              - targets:
                  - '100.115.45.53:9100'
                  - '100.115.45.53:9558'

    - role: portainer-master
      vars:
        portainer_admin_password: "{{ portainer_admin_password }}"

- name: "Gopher site"
  hosts: copenhagen-b
  roles:
    - role: gopher-site
  vars:
    gopher_repo_url: https://github.com/rwejlgaard/pez-gopher
