---
- hosts: london
  name: test
  gather_facts: true
  tasks:
    #- name: get token
      #set_fact:
        #k3s_token: item
      #with_file:
        #- "/var/lib/rancher/k3s/server/node-token"
      #when: "'-a' in inventory_hostname"

    #- debug:
        #msg: "{{ hostvars[inventory_hostname.split('-')[0] + '-a']['k3s_token'] }}"

    - debug:
        var: item
      with_file:
        - /var/lib/rancher/k3s/server/node-token
