{
 "title": "Download Client",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "torrent",
    "label": "torrent",
    "query": "label_values(transmission_torrent_added, name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "[Download Client Link](https://download.pez.sh/transmission)"
   }
  },
  {
   "title": "Global Speeds",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_download_speed_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "transmission_session_stats_upload_speed_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downloads (bytes/second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(transmission_torrent_download_bytes{name=~\"$torrent\"}) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uploads (bytes/second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(transmission_torrent_upload_bytes{name=~\"$torrent\"}) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Torrents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(transmission_torrent_status{name=~\"$torrent\"}) by (name)"
    },
    {
     "expr": "max(transmission_torrent_done{name=~\"$torrent\"}) by (name)"
    },
    {
     "expr": "max(transmission_torrent_download_bytes{name=~\"$torrent\"}) by (name)"
    },
    {
     "expr": "max(transmission_torrent_upload_bytes{name=~\"$torrent\"}) by (name)"
    },
    {
     "expr": "max(transmission_torrent_seeders{name=~\"$torrent\"}) by (name)"
    }
   ]
  }
 ]
}