- name: Install fish shell
  package:
    name: fish
    state: present

- name: Install chsh for Alpine
  package:
    name: shadow
    state: present
  when: ansible_os_family == 'Alpine'

- name: Get Fish shell path
  command: which fish
  changed_when: false
  register: fish_path

- name: Set Fish shell as default
  command: chsh -s {{ fish_path.stdout }}
  when: ansible_user_shell != fish_path.stdout
