- name: Make sure requests is installed on Alpine
  apk:
    name: py3-requests
    state: present
  when: ansible_os_family == 'Alpine'

- name: Node-exporter container
  community.general.docker_container:
    name: node_exporter
    state: started
    image: "quay.io/prometheus/node-exporter:{{ node_exporter_version }}"
    detach: true
    restart_policy: always
    network_mode: host
    volumes:
      - "/:/host:ro,rslave"
    command: "--path.rootfs=/host"
