- name: Make sure requests is installed on Alpine
  apk:
    name: py3-requests
    state: present
  when: ansible_os_family == 'Alpine'

- name: Portainer-agent container
  community.general.docker_container:
    name: portainer_agent
    state: started
    image: "portainer/agent:{{ agent_version }}"
    detach: true
    restart_policy: always
    published_ports:
      - "{{ agent_port }}:{{ agent_port }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
